apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mqttlistener
  namespace: cluster-config
spec:
  targetNamespace: visualfurnaces
  releaseName: mqtt
  chart:
    spec:
      chart: spring-boot
      sourceRef:
        kind: HelmRepository
        name: iotfruehwia
        namespace: cluster-config
  interval: 5m
  install:
    remediation:
      retries: 3
  # Default values
  # https://github.com/stefanprodan/podinfo/blob/master/charts/podinfo/values.yaml
  values:
    mqttserver: mosquitto.mosquitto.svc.cluster.local:1883
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
