apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: iotfruehwia
spec:
  interval: 30m
  url: oci://iotfruehwia.azurecr.io/helm/v1/repo
  provider: "azure"
  secretRef:
    name: oci-creds
