apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: iotfruehwia
spec:
  interval: 30m
  type: "oci"
  url: oci://iotfruehwia.azurecr.io/helm/v1/repo
  secretRef:
    name: oci-creds
