apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mosquitto
  namespace: cluster-config
spec:
  targetNamespace: mosquitto
  releaseName: mosquitto
  chart:
    spec:
      chart: mosquitto
      sourceRef:
        kind: HelmRepository
        name: t3n
        namespace: cluster-config
      version: "2.4.1"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: mosquitto-values
