apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: kafka
  demo: kafka-demo

namespace: kafka-kraft

resources:
- namespace.yaml
- statefulset.yaml
- service.yaml
- persistencevolume.yaml
- pvc.yaml
