apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mqttlistener
  namespace: cluster-config
spec:
  chart:
    spec:
      version: "0.1.0"
  test:
    enable: false
  values:
    ingress:
      hosts:
        - host: visualfurnaces.staging
          paths:
            - path: /
              pathType: ImplementationSpecific
