apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: route-unsecured
spec:
  host: iot-k8s-edge.northeurope.cloudapp.azure.com
  path: "/test"   
  
  to:
    kind: Service
    name:  helloweb-service